# Generated by Django 5.2.15 on 2026-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_layer', '0027_remove_jenks_bins'),
        ('terra_layer', '0030_remove_jenks_bins'),
    ]

    operations = [
    ]
