# Generated by Django 5.2.16 on 2026-08-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_layer', '0031_merge_0027_remove_jenks_bins_0030_remove_jenks_bins'),
        ('terra_layer', '0033_alter_extent_pictogram'),
    ]

    operations = [
    ]
