# Generated by Django 5.2.15 on 2026-07-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosource', '0016_alter_source_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPackageSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geosource.source')),
                ('file', models.FileField(upload_to='geosource/geopackage/%Y/')),
                ('layer_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'GeoPackage Source',
                'verbose_name_plural': 'GeoPackage Sources',
            },
            bases=('geosource.source',),
        ),
    ]
