# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosource', '0017_geopackagesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='original_srid', # c'est ici qu'on enregistre le CRS de base
            field=models.IntegerField(blank=True, null=True),
        ),
    ]