# Generated by Django 5.2.12 on 2026-07-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosource', '0018_add_original_srid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFileSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geosource.source')),
                ('file', models.FileField(upload_to='geosource/geofile/%Y/')),
                ('layer_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'GeoFile Source',
                'verbose_name_plural': 'GeoFile Sources',
            },
            bases=('geosource.source',),
        ),
    ]
