# Generated by Django 5.2.15 on 2026-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosource', '0017_alter_source_options'),
        ('geosource', '0019_geofilesource'),
    ]

    operations = [
    ]
